title: Gonçalo Sousa
profile_img: /assets/img/profile.png
icon_img: /assets/img/favicon.ico

name: "Gonçalo Sousa"
job: "DevOps Engineer"

address: Seixal, Portugal
linkedin_username: gsousa7
github_username: gsousa7
#phone_number: "+351 925 857 381"
#email: goncalodcsousa@gmail.com

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
- _posts/
- resources/
- vendor/

plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
